name: Latest jjsantoso blog post workflow
on:
  schedule:
    # Runs every week
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://blog.jjsantoso.com/feed.xml"
          commit_message: "Update blog.jjsantoso.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
